#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace absensi.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="absensi")]
	public partial class absensiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertabsensi_absensi(absensi_absensi instance);
    partial void Updateabsensi_absensi(absensi_absensi instance);
    partial void Deleteabsensi_absensi(absensi_absensi instance);
    partial void Insertabsensi_karyawan(absensi_karyawan instance);
    partial void Updateabsensi_karyawan(absensi_karyawan instance);
    partial void Deleteabsensi_karyawan(absensi_karyawan instance);
    partial void Insertabsensi_upah(absensi_upah instance);
    partial void Updateabsensi_upah(absensi_upah instance);
    partial void Deleteabsensi_upah(absensi_upah instance);
    #endregion
		
		public absensiDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["absensiConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public absensiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public absensiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public absensiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public absensiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<absensi_absensi> absensi_absensis
		{
			get
			{
				return this.GetTable<absensi_absensi>();
			}
		}
		
		public System.Data.Linq.Table<absensi_karyawan> absensi_karyawans
		{
			get
			{
				return this.GetTable<absensi_karyawan>();
			}
		}
		
		public System.Data.Linq.Table<absensi_upah> absensi_upahs
		{
			get
			{
				return this.GetTable<absensi_upah>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[absensi.absensi]")]
	public partial class absensi_absensi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.DateTime _tanggal;
		
		private System.TimeSpan _jam_masuk;
		
		private System.TimeSpan _jam_keluar;
		
		private int _id_karyawan;
		
		private EntityRef<absensi_karyawan> _absensi_karyawan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntanggalChanging(System.DateTime value);
    partial void OntanggalChanged();
    partial void Onjam_masukChanging(System.TimeSpan value);
    partial void Onjam_masukChanged();
    partial void Onjam_keluarChanging(System.TimeSpan value);
    partial void Onjam_keluarChanged();
    partial void Onid_karyawanChanging(int value);
    partial void Onid_karyawanChanged();
    #endregion
		
		public absensi_absensi()
		{
			this._absensi_karyawan = default(EntityRef<absensi_karyawan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tanggal", DbType="Date NOT NULL")]
		public System.DateTime tanggal
		{
			get
			{
				return this._tanggal;
			}
			set
			{
				if ((this._tanggal != value))
				{
					this.OntanggalChanging(value);
					this.SendPropertyChanging();
					this._tanggal = value;
					this.SendPropertyChanged("tanggal");
					this.OntanggalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jam_masuk", DbType="Time NOT NULL")]
		public System.TimeSpan jam_masuk
		{
			get
			{
				return this._jam_masuk;
			}
			set
			{
				if ((this._jam_masuk != value))
				{
					this.Onjam_masukChanging(value);
					this.SendPropertyChanging();
					this._jam_masuk = value;
					this.SendPropertyChanged("jam_masuk");
					this.Onjam_masukChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jam_keluar", DbType="Time NOT NULL")]
		public System.TimeSpan jam_keluar
		{
			get
			{
				return this._jam_keluar;
			}
			set
			{
				if ((this._jam_keluar != value))
				{
					this.Onjam_keluarChanging(value);
					this.SendPropertyChanging();
					this._jam_keluar = value;
					this.SendPropertyChanged("jam_keluar");
					this.Onjam_keluarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_karyawan", DbType="Int NOT NULL")]
		public int id_karyawan
		{
			get
			{
				return this._id_karyawan;
			}
			set
			{
				if ((this._id_karyawan != value))
				{
					if (this._absensi_karyawan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_karyawanChanging(value);
					this.SendPropertyChanging();
					this._id_karyawan = value;
					this.SendPropertyChanged("id_karyawan");
					this.Onid_karyawanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="absensi_karyawan_absensi_absensi", Storage="_absensi_karyawan", ThisKey="id_karyawan", OtherKey="id", IsForeignKey=true)]
		public absensi_karyawan absensi_karyawan
		{
			get
			{
				return this._absensi_karyawan.Entity;
			}
			set
			{
				absensi_karyawan previousValue = this._absensi_karyawan.Entity;
				if (((previousValue != value) 
							|| (this._absensi_karyawan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._absensi_karyawan.Entity = null;
						previousValue.absensi_absensis.Remove(this);
					}
					this._absensi_karyawan.Entity = value;
					if ((value != null))
					{
						value.absensi_absensis.Add(this);
						this._id_karyawan = value.id;
					}
					else
					{
						this._id_karyawan = default(int);
					}
					this.SendPropertyChanged("absensi_karyawan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[absensi.karyawan]")]
	public partial class absensi_karyawan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _nip;
		
		private string _nama;
		
		private string _alamat;
		
		private int _id_upah;
		
		private EntitySet<absensi_absensi> _absensi_absensis;
		
		private EntityRef<absensi_upah> _absensi_upah;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnipChanging(int value);
    partial void OnnipChanged();
    partial void OnnamaChanging(string value);
    partial void OnnamaChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    partial void Onid_upahChanging(int value);
    partial void Onid_upahChanged();
    #endregion
		
		public absensi_karyawan()
		{
			this._absensi_absensis = new EntitySet<absensi_absensi>(new Action<absensi_absensi>(this.attach_absensi_absensis), new Action<absensi_absensi>(this.detach_absensi_absensis));
			this._absensi_upah = default(EntityRef<absensi_upah>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nip", DbType="Int NOT NULL")]
		public int nip
		{
			get
			{
				return this._nip;
			}
			set
			{
				if ((this._nip != value))
				{
					this.OnnipChanging(value);
					this.SendPropertyChanging();
					this._nip = value;
					this.SendPropertyChanged("nip");
					this.OnnipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama", DbType="NChar(255) NOT NULL", CanBeNull=false)]
		public string nama
		{
			get
			{
				return this._nama;
			}
			set
			{
				if ((this._nama != value))
				{
					this.OnnamaChanging(value);
					this.SendPropertyChanging();
					this._nama = value;
					this.SendPropertyChanged("nama");
					this.OnnamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="NChar(255) NOT NULL", CanBeNull=false)]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_upah", DbType="Int NOT NULL")]
		public int id_upah
		{
			get
			{
				return this._id_upah;
			}
			set
			{
				if ((this._id_upah != value))
				{
					if (this._absensi_upah.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_upahChanging(value);
					this.SendPropertyChanging();
					this._id_upah = value;
					this.SendPropertyChanged("id_upah");
					this.Onid_upahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="absensi_karyawan_absensi_absensi", Storage="_absensi_absensis", ThisKey="id", OtherKey="id_karyawan")]
		public EntitySet<absensi_absensi> absensi_absensis
		{
			get
			{
				return this._absensi_absensis;
			}
			set
			{
				this._absensi_absensis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="absensi_upah_absensi_karyawan", Storage="_absensi_upah", ThisKey="id_upah", OtherKey="id", IsForeignKey=true)]
		public absensi_upah absensi_upah
		{
			get
			{
				return this._absensi_upah.Entity;
			}
			set
			{
				absensi_upah previousValue = this._absensi_upah.Entity;
				if (((previousValue != value) 
							|| (this._absensi_upah.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._absensi_upah.Entity = null;
						previousValue.absensi_karyawans.Remove(this);
					}
					this._absensi_upah.Entity = value;
					if ((value != null))
					{
						value.absensi_karyawans.Add(this);
						this._id_upah = value.id;
					}
					else
					{
						this._id_upah = default(int);
					}
					this.SendPropertyChanged("absensi_upah");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_absensi_absensis(absensi_absensi entity)
		{
			this.SendPropertyChanging();
			entity.absensi_karyawan = this;
		}
		
		private void detach_absensi_absensis(absensi_absensi entity)
		{
			this.SendPropertyChanging();
			entity.absensi_karyawan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[absensi.upah]")]
	public partial class absensi_upah : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _nama_golongan;
		
		private int _gaji;
		
		private EntitySet<absensi_karyawan> _absensi_karyawans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onnama_golonganChanging(string value);
    partial void Onnama_golonganChanged();
    partial void OngajiChanging(int value);
    partial void OngajiChanged();
    #endregion
		
		public absensi_upah()
		{
			this._absensi_karyawans = new EntitySet<absensi_karyawan>(new Action<absensi_karyawan>(this.attach_absensi_karyawans), new Action<absensi_karyawan>(this.detach_absensi_karyawans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_golongan", DbType="NChar(255) NOT NULL", CanBeNull=false)]
		public string nama_golongan
		{
			get
			{
				return this._nama_golongan;
			}
			set
			{
				if ((this._nama_golongan != value))
				{
					this.Onnama_golonganChanging(value);
					this.SendPropertyChanging();
					this._nama_golongan = value;
					this.SendPropertyChanged("nama_golongan");
					this.Onnama_golonganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gaji", DbType="Int NOT NULL")]
		public int gaji
		{
			get
			{
				return this._gaji;
			}
			set
			{
				if ((this._gaji != value))
				{
					this.OngajiChanging(value);
					this.SendPropertyChanging();
					this._gaji = value;
					this.SendPropertyChanged("gaji");
					this.OngajiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="absensi_upah_absensi_karyawan", Storage="_absensi_karyawans", ThisKey="id", OtherKey="id_upah")]
		public EntitySet<absensi_karyawan> absensi_karyawans
		{
			get
			{
				return this._absensi_karyawans;
			}
			set
			{
				this._absensi_karyawans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_absensi_karyawans(absensi_karyawan entity)
		{
			this.SendPropertyChanging();
			entity.absensi_upah = this;
		}
		
		private void detach_absensi_karyawans(absensi_karyawan entity)
		{
			this.SendPropertyChanging();
			entity.absensi_upah = null;
		}
	}
}
#pragma warning restore 1591
